remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: List of Documents and Blogs101
description: **Bookmarks for the HELLO WORLD page101**
show_downloads: "true"
